language: node_js

node_js:
  - '6'
  - '7'

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &

script:
  - node --version
  - npm --version
  - npm install
  - npm run lint

cache:
  directories:
    - node_modules

notifications:
  email:
    recipients:
      - m.davinahn@gmail.com